# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\MainWindow_v1.ui'
#
# Created: Tue Jun 04 22:32:00 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(260, 264)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Input-Gaming.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.stackedWidget_main = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setObjectName(_fromUtf8("stackedWidget_main"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_header = QtGui.QFrame(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_header.sizePolicy().hasHeightForWidth())
        self.frame_header.setSizePolicy(sizePolicy)
        self.frame_header.setMinimumSize(QtCore.QSize(250, 108))
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 108))
        self.frame_header.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_header.setObjectName(_fromUtf8("frame_header"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_header)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_image_buffer = QtGui.QFrame(self.frame_header)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_image_buffer.sizePolicy().hasHeightForWidth())
        self.frame_image_buffer.setSizePolicy(sizePolicy)
        self.frame_image_buffer.setMinimumSize(QtCore.QSize(250, 108))
        self.frame_image_buffer.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_image_buffer.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_image_buffer.setLineWidth(1)
        self.frame_image_buffer.setObjectName(_fromUtf8("frame_image_buffer"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_image_buffer)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label = QtGui.QLabel(self.frame_image_buffer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 108))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/assets/images/landingLogo_v1.png")))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_image_buffer)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.frame_header)
        self.frame_buttons = QtGui.QFrame(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons.sizePolicy().hasHeightForWidth())
        self.frame_buttons.setSizePolicy(sizePolicy)
        self.frame_buttons.setMinimumSize(QtCore.QSize(250, 118))
        self.frame_buttons.setMaximumSize(QtCore.QSize(16777215, 118))
        self.frame_buttons.setFrameShape(QtGui.QFrame.Box)
        self.frame_buttons.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_buttons.setObjectName(_fromUtf8("frame_buttons"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_buttons)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setMargin(5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.commandLinkButton_authenticate = QtGui.QCommandLinkButton(self.frame_buttons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-Web.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_authenticate.setIcon(icon1)
        self.commandLinkButton_authenticate.setAutoDefault(False)
        self.commandLinkButton_authenticate.setDefault(False)
        self.commandLinkButton_authenticate.setObjectName(_fromUtf8("commandLinkButton_authenticate"))
        self.verticalLayout_7.addWidget(self.commandLinkButton_authenticate)
        self.commandLinkButton_manage_accounts = QtGui.QCommandLinkButton(self.frame_buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton_manage_accounts.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_manage_accounts.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-System.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_manage_accounts.setIcon(icon2)
        self.commandLinkButton_manage_accounts.setObjectName(_fromUtf8("commandLinkButton_manage_accounts"))
        self.verticalLayout_7.addWidget(self.commandLinkButton_manage_accounts)
        self.verticalLayout_5.addWidget(self.frame_buttons)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.stackedWidget_main.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget_chat = QtGui.QTabWidget(self.page_4)
        self.tabWidget_chat.setObjectName(_fromUtf8("tabWidget_chat"))
        self.chatview = QtGui.QWidget()
        self.chatview.setObjectName(_fromUtf8("chatview"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.chatview)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidget_chat = QtGui.QTreeWidget(self.chatview)
        self.treeWidget_chat.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeWidget_chat.setAlternatingRowColors(True)
        self.treeWidget_chat.setIndentation(0)
        self.treeWidget_chat.setRootIsDecorated(False)
        self.treeWidget_chat.setItemsExpandable(False)
        self.treeWidget_chat.setAnimated(True)
        self.treeWidget_chat.setObjectName(_fromUtf8("treeWidget_chat"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-Urgent.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget_chat.headerItem().setIcon(0, icon3)
        self.treeWidget_chat.headerItem().setIcon(1, icon)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Dialog-Warning.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget_chat.headerItem().setIcon(2, icon4)
        self.treeWidget_chat.header().setCascadingSectionResizes(True)
        self.treeWidget_chat.header().setDefaultSectionSize(75)
        self.treeWidget_chat.header().setMinimumSectionSize(10)
        self.treeWidget_chat.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.treeWidget_chat)
        self.frame_chat_input = QtGui.QFrame(self.chatview)
        self.frame_chat_input.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_chat_input.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_chat_input.setObjectName(_fromUtf8("frame_chat_input"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_chat_input)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_chat_input = QtGui.QLineEdit(self.frame_chat_input)
        self.lineEdit_chat_input.setObjectName(_fromUtf8("lineEdit_chat_input"))
        self.horizontalLayout_2.addWidget(self.lineEdit_chat_input)
        self.pushButton_chat_send = QtGui.QPushButton(self.frame_chat_input)
        self.pushButton_chat_send.setIcon(icon4)
        self.pushButton_chat_send.setAutoDefault(False)
        self.pushButton_chat_send.setDefault(False)
        self.pushButton_chat_send.setObjectName(_fromUtf8("pushButton_chat_send"))
        self.horizontalLayout_2.addWidget(self.pushButton_chat_send)
        self.verticalLayout_2.addWidget(self.frame_chat_input)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Computer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_chat.addTab(self.chatview, icon5, _fromUtf8(""))
        self.users = QtGui.QWidget()
        self.users.setObjectName(_fromUtf8("users"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.users)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setMargin(5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.treeWidget_users = QtGui.QTreeWidget(self.users)
        self.treeWidget_users.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeWidget_users.setAlternatingRowColors(True)
        self.treeWidget_users.setRootIsDecorated(False)
        self.treeWidget_users.setUniformRowHeights(True)
        self.treeWidget_users.setItemsExpandable(False)
        self.treeWidget_users.setExpandsOnDoubleClick(False)
        self.treeWidget_users.setObjectName(_fromUtf8("treeWidget_users"))
        self.treeWidget_users.headerItem().setIcon(0, icon)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-Important.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget_users.headerItem().setIcon(1, icon6)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-Generic.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget_users.headerItem().setIcon(2, icon7)
        self.treeWidget_users.header().setDefaultSectionSize(111)
        self.treeWidget_users.header().setMinimumSectionSize(20)
        self.verticalLayout_8.addWidget(self.treeWidget_users)
        self.tabWidget_chat.addTab(self.users, icon1, _fromUtf8(""))
        self.statistics = QtGui.QWidget()
        self.statistics.setObjectName(_fromUtf8("statistics"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.statistics)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setMargin(5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget_chat.addTab(self.statistics, icon2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_chat)
        self.stackedWidget_main.addWidget(self.page_4)
        self.verticalLayout_4.addWidget(self.stackedWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 260, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Dialog-Error.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUser_Guide = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Edit-Find.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUser_Guide.setIcon(icon9)
        self.actionUser_Guide.setObjectName(_fromUtf8("actionUser_Guide"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Dialog-Question.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon10)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(0)
        self.tabWidget_chat.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.lineEdit_chat_input, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.pushButton_chat_send.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Twitch IRC Bot v1.0", None))
        self.commandLinkButton_authenticate.setText(_translate("MainWindow", "Authenticate as: opopbot", None))
        self.commandLinkButton_authenticate.setDescription(_translate("MainWindow", "Room: #rpigamer", None))
        self.commandLinkButton_manage_accounts.setText(_translate("MainWindow", "Manage Bot Accounts", None))
        self.commandLinkButton_manage_accounts.setDescription(_translate("MainWindow", "Configure Credentials", None))
        self.treeWidget_chat.setSortingEnabled(True)
        self.treeWidget_chat.headerItem().setText(0, _translate("MainWindow", "Time", None))
        self.treeWidget_chat.headerItem().setText(1, _translate("MainWindow", "Name", None))
        self.treeWidget_chat.headerItem().setText(2, _translate("MainWindow", "Message", None))
        self.pushButton_chat_send.setText(_translate("MainWindow", "Send", None))
        self.tabWidget_chat.setTabText(self.tabWidget_chat.indexOf(self.chatview), _translate("MainWindow", "Chat", None))
        self.treeWidget_users.setSortingEnabled(True)
        self.treeWidget_users.headerItem().setText(0, _translate("MainWindow", "Nick", None))
        self.treeWidget_users.headerItem().setText(1, _translate("MainWindow", "Operator", None))
        self.treeWidget_users.headerItem().setText(2, _translate("MainWindow", "Voiced", None))
        self.tabWidget_chat.setTabText(self.tabWidget_chat.indexOf(self.users), _translate("MainWindow", "Users", None))
        self.tabWidget_chat.setTabText(self.tabWidget_chat.indexOf(self.statistics), _translate("MainWindow", "Statistics", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionUser_Guide.setText(_translate("MainWindow", "User Guide", None))
        self.actionUser_Guide.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+I", None))

import media_rc
