# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\MainWindow_v1.ui'
#
# Created: Sat Jun 01 11:26:13 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(260, 228)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/Gnome-Input-Gaming.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.stackedWidget_main = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setObjectName(_fromUtf8("stackedWidget_main"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setMargin(5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame = QtGui.QFrame(self.page_3)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.frame)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/assets/images/landingLogo_v1.png")))
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.frame)
        self.commandLinkButton_authenticate = QtGui.QCommandLinkButton(self.page_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-Web.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_authenticate.setIcon(icon1)
        self.commandLinkButton_authenticate.setAutoDefault(True)
        self.commandLinkButton_authenticate.setDefault(True)
        self.commandLinkButton_authenticate.setObjectName(_fromUtf8("commandLinkButton_authenticate"))
        self.verticalLayout_5.addWidget(self.commandLinkButton_authenticate)
        self.frame_2 = QtGui.QFrame(self.page_3)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_manage_accounts = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_manage_accounts.sizePolicy().hasHeightForWidth())
        self.pushButton_manage_accounts.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Dialog-Password.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_manage_accounts.setIcon(icon2)
        self.pushButton_manage_accounts.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_manage_accounts.setFlat(False)
        self.pushButton_manage_accounts.setObjectName(_fromUtf8("pushButton_manage_accounts"))
        self.horizontalLayout_2.addWidget(self.pushButton_manage_accounts)
        spacerItem3 = QtGui.QSpacerItem(56, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.frame_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.stackedWidget_main.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.page_4)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.chatview = QtGui.QWidget()
        self.chatview.setObjectName(_fromUtf8("chatview"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.chatview)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeWidget_chat = QtGui.QTreeWidget(self.chatview)
        self.treeWidget_chat.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeWidget_chat.setAlternatingRowColors(True)
        self.treeWidget_chat.setIndentation(0)
        self.treeWidget_chat.setRootIsDecorated(False)
        self.treeWidget_chat.setItemsExpandable(False)
        self.treeWidget_chat.setAnimated(True)
        self.treeWidget_chat.setObjectName(_fromUtf8("treeWidget_chat"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-Urgent.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget_chat.headerItem().setIcon(0, icon3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Input-Gaming.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget_chat.headerItem().setIcon(1, icon4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Dialog-Warning.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget_chat.headerItem().setIcon(2, icon5)
        self.treeWidget_chat.header().setCascadingSectionResizes(True)
        self.treeWidget_chat.header().setDefaultSectionSize(75)
        self.treeWidget_chat.header().setMinimumSectionSize(10)
        self.treeWidget_chat.header().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.treeWidget_chat)
        self.lineEdit = QtGui.QLineEdit(self.chatview)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Computer.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.chatview, icon6, _fromUtf8(""))
        self.statistics = QtGui.QWidget()
        self.statistics.setObjectName(_fromUtf8("statistics"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.statistics)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setMargin(5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Emblem-System.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.statistics, icon7, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.stackedWidget_main.addWidget(self.page_4)
        self.verticalLayout_4.addWidget(self.stackedWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 260, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Dialog-Error.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUser_Guide = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Edit-Find.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUser_Guide.setIcon(icon9)
        self.actionUser_Guide.setObjectName(_fromUtf8("actionUser_Guide"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/Gnome-Dialog-Question.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon10)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Twitch IRC Bot v1.0", None))
        self.commandLinkButton_authenticate.setText(_translate("MainWindow", "Authenticate as: opopbot", None))
        self.commandLinkButton_authenticate.setDescription(_translate("MainWindow", "Room: #rpigamer", None))
        self.pushButton_manage_accounts.setText(_translate("MainWindow", "Manage Accounts ", None))
        self.treeWidget_chat.setSortingEnabled(True)
        self.treeWidget_chat.headerItem().setText(0, _translate("MainWindow", "Time", None))
        self.treeWidget_chat.headerItem().setText(1, _translate("MainWindow", "Name", None))
        self.treeWidget_chat.headerItem().setText(2, _translate("MainWindow", "Message", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chatview), _translate("MainWindow", "Chat", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistics), _translate("MainWindow", "Statistics", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionUser_Guide.setText(_translate("MainWindow", "User Guide", None))
        self.actionUser_Guide.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+I", None))

import media_rc
